version: '3'

services:
  backend:
    build:
      context: ./web_pro 
    command: gunicorn web_pro.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./front-end/users
    volumes:
      - react_bulid:/react/build
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports: 
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_bulid:/var/www/react
    depends_on:
      - backend
      - frontend

volumes:
  react_bulid:

